services:
  better-marketplace_db:
    container_name: better-marketplace_db
    image: postgis/postgis
    environment:
    - POSTGRES_PASSWORD=changemelater
    - POSTGRES_USER=marketplace_user
    - POSTGRES_DB=marketplace
    volumes:
    - marketplace-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  marketplace-app:
    container_name: better-marketplace
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://better-marketplace_db:5432/marketplace
    - SPRING_DATASOURCE_USERNAME=marketplace_user
    - SPRING_DATASOURCE_PASSWORD=changemelater
    - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
    - better-marketplace_db
    ports:
    - "8080:8080"

volumes:
  marketplace-data: { }
