services:
  marketplace-database:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: changeit
      POSTGRES_USER: marketplace
      POSTGRES_DB: marketplace
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  marketplace-app:
    container_name: better-marketplace
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
    - marketplace-database
    ports:
    - 8080:8080

volumes:
  postgres-data: {}
