spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  application:
    name: better-marketplace
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    driver-class-name: org.postgresql.Driver
    username: marketplace
    password: changeit

file-service:
  storage-directory: /files