server:
  servlet:
    context-path: '/api/better-marketplace'

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  application:
    name: better-marketplace
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  openfeign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 10000
          loggerLevel: basic
app:
  security:
    token:
      expiration-hours: 168
clients:
  open-data-client:
    url: 'https://data.opendatasoft.com/api/explore/v2.1/catalog/datasets/geonames-postal-code@public/exports'
